// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxireahjcrxuhlivlaks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54aXJlYWhqY3J4dWhsaXZsYWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODQ1NzQsImV4cCI6MjA2ODM2MDU3NH0.0tqE31-OFF65LvPL2wn_8z7sY-nSbo1YEpl1J9-DC-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
const isClient = typeof window !== 'undefined';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isClient ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});